CREATE DATABASE EduSys
GO
USE EduSys
GO
CREATE TABLE NHANVIEN(
	MANV NVARCHAR(20) PRIMARY KEY NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	VAITRO BIT NOT NULL --0 LÀ NHÂN VIÊN ,1 LÀ TRƯỞNG PHÒNG
)
GO
CREATE TABLE CHUYENDE(
	MACD NCHAR(5) PRIMARY KEY NOT NULL,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	HINH NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(255) NOT NULL
)
GO
CREATE TABLE KHOAHOC(
	MAKH INT PRIMARY KEY IDENTITY(1,1),
	MACD NCHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKHAIGIANG DATE NOT NULL,
	GHICHU NVARCHAR(255) NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYTAO DATE NOT NULL, --NGÀY ĐĂNG KÝ
	FOREIGN KEY(MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO
CREATE TABLE NGUOIHOC(
	MANH NCHAR(7) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT NOT NULL, --0 LÀ NỮ , 1 LÀ NAM
	NGAYSINH DATE NOT NULL,
	DIENTHOAI NVARCHAR(24) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(255) NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYDANGKY  DATE NOT NULL,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO
CREATE TABLE HOCVIEN(
	MAHV INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MAKH INT NOT NULL,
	MANH NCHAR(7) NOT NULL,
	DIEM FLOAT NOT NULL,
)

ALTER TABLE HOCVIEN ADD FOREIGN KEY(MAKH) REFERENCES KHOAHOC(MAKH) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE HOCVIEN ADD FOREIGN KEY(MANH) REFERENCES NGUOIHOC(MANH) ON DELETE NO ACTION ON UPDATE CASCADE -- LỖI CHƯA BIẾT 

